# Generated by Django 4.2.11 on 2025-02-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField(verbose_name='Date Released')),
                ('duration', models.IntegerField(verbose_name='Duration')),
            ],
        ),
    ]
