# Generated by Django 4.2.11 on 2025-02-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='testfield',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
