# Generated by Django 4.2.11 on 2025-02-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_movie_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='testfield',
        ),
    ]
